### ISSUE TITLE
cURL command error

### ISSUE THREAD

**Issue by feedju** [testdrivenio/flask-vue-crud#1]
Every time I try to run this cURL command I get this error. Did some Googling and it looks like 'get' in line 52 of the code in ap.py at the point in your tutorial:

With the Flask server running, you can test the POST route in a new terminal tab:

$ curl -X POST http://localhost:5000/books -d \
  '{"title": "1Q84", "author": "Haruki Murakami", "read": "true"}' \
  -H 'Content-Type: application/json'

Any idea? Thanks! Great tutorial by the way. 

```
Traceback (most recent call last):
  File "C:\Users\1010\Desktop\crudTest\flask-vue-crud\server\venv\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\1010\Desktop\crudTest\flask-vue-crud\server\venv\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\1010\Desktop\crudTest\flask-vue-crud\server\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\1010\Desktop\crudTest\flask-vue-crud\server\venv\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\1010\Desktop\crudTest\flask-vue-crud\server\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\1010\Desktop\crudTest\flask-vue-crud\server\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\1010\Desktop\crudTest\flask-vue-crud\server\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\1010\Desktop\crudTest\flask-vue-crud\server\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\1010\Desktop\crudTest\flask-vue-crud\server\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\1010\Desktop\crudTest\flask-vue-crud\server\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\1010\Desktop\crudTest\flask-vue-crud\server\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\1010\Desktop\crudTest\flask-vue-crud\server\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\1010\Desktop\crudTest\flask-vue-crud\server\app.py", line 52, in all_books
    'title': post_data.get('title'),
AttributeError: 'NoneType' object has no attribute 'get'

-->
curl: (3) [globbing] unmatched brace in column 2
curl: (6) Could not resolve host: 1Q84,
curl: (6) Could not resolve host: author
curl: (3) Host name 'Haruki Murakami,' contains bad letter
curl: (6) Could not resolve host: read
curl: (3) [globbing] unmatched close brace/bracket in column 5
curl: (6) Could not resolve host: \
curl: (6) Could not resolve host: application



```

**Comment by jay3ss** [comment]
I'm having the same issue
